### ISSUE TITLE
Goes into exception with Oid like this iso.3.6.1.2.1.1.1.0

### ISSUE THREAD

**Issue by terminator891** [hh-h/aiosnmp#17]
It is going into exception with a valid oid like this iso.3.6.1.2.1.1.1.0. Is oids like that not supported?

`Traceback (most recent call last):
  File "/home/humayun/PycharmProjects/asynciotesting/snmp/asyncio_snmp_testing.py", line 21, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/humayun/PycharmProjects/asynciotesting/snmp/asyncio_snmp_testing.py", line 16, in main
    for res in await snmp.get("iso.3.6.1.2.1.1.1.0"):
  File "/home/humayun/PycharmProjects/asynciotesting/.env/lib/python3.7/site-packages/aiosnmp/snmp.py", line 63, in get
    return await self._send(message)
  File "/home/humayun/PycharmProjects/asynciotesting/.env/lib/python3.7/site-packages/aiosnmp/snmp.py", line 55, in _send
    return await self._protocol._send(message, *self._peername[:2])
  File "/home/humayun/PycharmProjects/asynciotesting/.env/lib/python3.7/site-packages/aiosnmp/protocols.py", line 138, in _send
    self.transport.sendto(message.encode())
  File "/home/humayun/PycharmProjects/asynciotesting/.env/lib/python3.7/site-packages/aiosnmp/message.py", line 147, in encode
    self.data.encode(encoder)
  File "/home/humayun/PycharmProjects/asynciotesting/.env/lib/python3.7/site-packages/aiosnmp/message.py", line 80, in encode
    varbind.encode(encoder)
  File "/home/humayun/PycharmProjects/asynciotesting/.env/lib/python3.7/site-packages/aiosnmp/message.py", line 57, in encode
    encoder.write(self._oid, Number.ObjectIdentifier)
  File "/home/humayun/PycharmProjects/asynciotesting/.env/lib/python3.7/site-packages/aiosnmp/asn1.py", line 168, in write
    value = self._encode_value(nr, value)
  File "/home/humayun/PycharmProjects/asynciotesting/.env/lib/python3.7/site-packages/aiosnmp/asn1.py", line 245, in _encode_value
    return self._encode_object_identifier(value)
  File "/home/humayun/PycharmProjects/asynciotesting/.env/lib/python3.7/site-packages/aiosnmp/asn1.py", line 304, in _encode_object_identifier
    raise Error("Illegal object identifier")
aiosnmp.asn1.Error: Illegal object identifier

`

**Comment by hh-h** [comment]
The only oids with digits are supported. Oid can start from dot, valid examples: `1.3.6.1.2.1.1.1` or `.1.3.6.1.2.1.1.1`.
